
# For quick access of data in functions

keypadcodes=[0x62,0x59,0x5a,0x5b,0x5c,0x5d,0x5e,0x5f,0x60,0x61]

importantkeys={
    'space':0x2c,
    'backspace':0x2a,
    'enter':0x28,
    'caps lock':0x39,
    'esc':0x29,
    'tab':0x2b,
    'delete':0x4c,
    'right':0x4f,
    'left':0x50,
    'up':0x52,
    'down':0x51,
    'end':0x4d,
    'home':0x4a,
    'page up':0x4b,
    'page down':0x4e
}

essentialmodkeys={
    'ctrl':0x1,
    'shift':0x2,
    'alt':0x4,
    'right ctrl':0x10,
    'right shift':0x20,
    'alt gr':0x40
}

# key changes with or without pressing shift 
#Used to remove keys that are added while removing shift but removed after releasing shift
key_to_shiftheld={
  "a": "A",
  "b": "B",
  "c": "C",
  "d": "D",
  "e": "E",
  "f": "F",
  "g": "G",
  "h": "H",
  "i": "I",
  "j": "J",
  "k": "K",
  "l": "L",
  "m": "M",
  "n": "N",
  "o": "O",
  "p": "P",
  "q": "Q",
  "r": "R",
  "s": "S",
  "t": "T",
  "u": "U",
  "v": "V",
  "w": "W",
  "x": "X",
  "y": "Y",
  "z": "Z",
  "1": "!",
  "2": "@",
  "3": "#",
  "4": "$",
  "5": "%",
  "6": "^",
  "7": "&",
  "8": "*",
  "9": "(",
  "0": ")",
  "-": "_",
  "=": "+",
  "[": "{",
  "]": "}",
  ";": ":",
  "'": "\"",
  ",": "<",
  ".": ">",
  "/": "?",
  "`": "~",
  "\\": "|"
}

shiftheld_to_key={
  "A": "a",
  "B": "b",
  "C": "c",
  "D": "d",
  "E": "e",
  "F": "f",
  "G": "g",
  "H": "h",
  "I": "i",
  "J": "j",
  "K": "k",
  "L": "l",
  "M": "m",
  "N": "n",
  "O": "o",
  "P": "p",
  "Q": "q",
  "R": "r",
  "S": "s",
  "T": "t",
  "U": "u",
  "V": "v",
  "W": "w",
  "X": "x",
  "Y": "y",
  "Z": "z",
  "!": "1",
  "@": "2",
  "#": "3",
  "$": "4",
  "%": "5",
  "^": "6",
  "&": "7",
  "*": "8",
  "(": "9",
  ")": "0",
  "_": "-",
  "+": "=",
  "{": "[",
  "}": "]",
  ":": ";",
  "\"": "'",
  "<": ",",
  ">": ".",
  "?": "/",
  "~": "`",
  "|": "\\"
}


#keyboard library keyname to standard identifiable keyname
keyboard_library_keymapping={
    "ctrl":"KEY_MOD_LCTRL",
    "left ctrl":"KEY_MOD_LCTRL",
    "right ctrl":"KEY_MOD_RCTRL",
    "shift":"KEY_MOD_LSHIFT",
    "left shift":"KEY_MOD_LSHIFT",
    "right shift":"KEY_MOD_RSHIFT",
    "alt":"KEY_MOD_LALT",
    "alt l":"KEY_MOD_LALT",
    "alt gr":"KEY_MOD_RALT",
    "windows":"KEY_MOD_LMETA",
    "left windows":"KEY_MOD_LMETA",
    "right windows":"KEY_MOD_RMETA",
    "meta":"KEY_MOD_LMETA",
    "left meta":"KEY_MOD_LMETA",
    "right meta":"KEY_MOD_LMETA",
    "A": "KEY_A",
    "B": "KEY_B",
    "C": "KEY_C",
    "D": "KEY_D",
    "E": "KEY_E",
    "F": "KEY_F",
    "G": "KEY_G",
    "H": "KEY_H",
    "I": "KEY_I",
    "J": "KEY_J",
    "K": "KEY_K",
    "L": "KEY_L",
    "M": "KEY_M",
    "N": "KEY_N",
    "O": "KEY_O",
    "P": "KEY_P",
    "Q": "KEY_Q",
    "R": "KEY_R",
    "S": "KEY_S",
    "T": "KEY_T",
    "U": "KEY_U",
    "V": "KEY_V",
    "W": "KEY_W",
    "X": "KEY_X",
    "Y": "KEY_Y",
    "Z": "KEY_Z",
    "!": "KEY_1",
    "@": "KEY_2",
    "#": "KEY_3",
    "$": "KEY_4",
    "%": "KEY_5",
    "^": "KEY_6",
    "&": "KEY_7",
    "*": "KEY_8",
    "(": "KEY_9",
    ")": "KEY_0",
    "_": "KEY_MINUS",
    "+": "KEY_EQUAL",
    "{": "KEY_LEFTBRACE",
    "}": "KEY_RIGHTBRACE",
    "|": "KEY_BACKSLASH",
    ":": "KEY_SEMICOLON",
    "\"": "KEY_APOSTROPHE",
    "~": "KEY_GRAVE",
    "<": "KEY_COMMA",
    ">": "KEY_DOT",
    "?": "KEY_SLASH",
    "a": "KEY_A",
    "b": "KEY_B",
    "c": "KEY_C",
    "d": "KEY_D",
    "e": "KEY_E",
    "f": "KEY_F",
    "g": "KEY_G",
    "h": "KEY_H",
    "i": "KEY_I",
    "j": "KEY_J",
    "k": "KEY_K",
    "l": "KEY_L",
    "m": "KEY_M",
    "n": "KEY_N",
    "o": "KEY_O",
    "p": "KEY_P",
    "q": "KEY_Q",
    "r": "KEY_R",
    "s": "KEY_S",
    "t": "KEY_T",
    "u": "KEY_U",
    "v": "KEY_V",
    "w": "KEY_W",
    "x": "KEY_X",
    "y": "KEY_Y",
    "z": "KEY_Z",
    "1": "KEY_1",
    "2": "KEY_2",
    "3": "KEY_3",
    "4": "KEY_4",
    "5": "KEY_5",
    "6": "KEY_6",
    "7": "KEY_7",
    "8": "KEY_8",
    "9": "KEY_9",
    "0": "KEY_0",
    "enter": "KEY_ENTER",
    "esc": "KEY_ESC",
    "backspace": "KEY_BACKSPACE",
    "tab": "KEY_TAB",
    "space": "KEY_SPACE",
    "-": "KEY_MINUS",
    "=": "KEY_EQUAL",
    "[": "KEY_LEFTBRACE",
    "]": "KEY_RIGHTBRACE",
    "\\": "KEY_BACKSLASH",
    ";": "KEY_SEMICOLON",
    "'": "KEY_APOSTROPHE",
    "`": "KEY_GRAVE",
    ",": "KEY_COMMA",
    ".": "KEY_DOT",
    "/": "KEY_SLASH",
    "caps lock": "KEY_CAPSLOCK",
    "f1": "KEY_F1",
    "f2": "KEY_F2",
    "f3": "KEY_F3",
    "f4": "KEY_F4",
    "f5": "KEY_F5",
    "f6": "KEY_F6",
    "f7": "KEY_F7",
    "f8": "KEY_F8",
    "f9": "KEY_F9",
    "f10": "KEY_F10",
    "f11": "KEY_F11",
    "f12": "KEY_F12",
    "print screen": "KEY_SYSRQ",
    "scroll lock":"KEY_SCROLLLOCK",
    "pause":"KEY_PAUSE",
    "insert": "KEY_INSERT",
    "home": "KEY_HOME",
    "page up": "KEY_PAGEUP",
    "delete": "KEY_DELETE",
    "end": "KEY_END",
    "page down": "KEY_PAGEDOWN",
    "right": "KEY_RIGHT",
    "left": "KEY_LEFT",
    "down": "KEY_DOWN",
    "up": "KEY_UP",
    "num lock": "KEY_NUMLOCK",
    "/": "KEY_KPSLASH",
    "*": "KEY_KPASTERISK",
    "-": "KEY_KPMINUS",
    "+": "KEY_KPPLUS",
    "enter ": "KEY_KPENTER",
    "1": "KEY_KP1",
    "2": "KEY_KP2",
    "3": "KEY_KP3",
    "4": "KEY_KP4",
    "5": "KEY_KP5",
    "6": "KEY_KP6",
    "7": "KEY_KP7",
    "8": "KEY_KP8",
    "9": "KEY_KP9",
    "0": "KEY_KP0",
    "decimal": "KEY_KPDOT"
}

# Scancode of a standard keyname
stdkeyname_to_scancode={
    "KEY_NONE": "0x00",
    "KEY_ERR_OVF": "0x01",
    "KEY_A": "0x04",
    "KEY_B": "0x05",
    "KEY_C": "0x06",
    "KEY_D": "0x07",
    "KEY_E": "0x08",
    "KEY_F": "0x09",
    "KEY_G": "0x0a",
    "KEY_H": "0x0b",
    "KEY_I": "0x0c",
    "KEY_J": "0x0d",
    "KEY_K": "0x0e",
    "KEY_L": "0x0f",
    "KEY_M": "0x10",
    "KEY_N": "0x11",
    "KEY_O": "0x12",
    "KEY_P": "0x13",
    "KEY_Q": "0x14",
    "KEY_R": "0x15",
    "KEY_S": "0x16",
    "KEY_T": "0x17",
    "KEY_U": "0x18",
    "KEY_V": "0x19",
    "KEY_W": "0x1a",
    "KEY_X": "0x1b",
    "KEY_Y": "0x1c",
    "KEY_Z": "0x1d",
    "KEY_1": "0x1e",
    "KEY_2": "0x1f",
    "KEY_3": "0x20",
    "KEY_4": "0x21",
    "KEY_5": "0x22",
    "KEY_6": "0x23",
    "KEY_7": "0x24",
    "KEY_8": "0x25",
    "KEY_9": "0x26",
    "KEY_0": "0x27",
    "KEY_ENTER": "0x28",
    "KEY_ESC": "0x29",
    "KEY_BACKSPACE": "0x2a",
    "KEY_TAB": "0x2b",
    "KEY_SPACE": "0x2c",
    "KEY_MINUS": "0x2d",
    "KEY_EQUAL": "0x2e",
    "KEY_LEFTBRACE": "0x2f",
    "KEY_RIGHTBRACE": "0x30",
    "KEY_BACKSLASH": "0x31",
    "KEY_HASHTILDE": "0x32",
    "KEY_SEMICOLON": "0x33",
    "KEY_APOSTROPHE": "0x34",
    "KEY_GRAVE": "0x35",
    "KEY_COMMA": "0x36",
    "KEY_DOT": "0x37",
    "KEY_SLASH": "0x38",
    "KEY_CAPSLOCK": "0x39",
    "KEY_F1": "0x3a",
    "KEY_F2": "0x3b",
    "KEY_F3": "0x3c",
    "KEY_F4": "0x3d",
    "KEY_F5": "0x3e",
    "KEY_F6": "0x3f",
    "KEY_F7": "0x40",
    "KEY_F8": "0x41",
    "KEY_F9": "0x42",
    "KEY_F10": "0x43",
    "KEY_F11": "0x44",
    "KEY_F12": "0x45",
    "KEY_SYSRQ": "0x46",
    "KEY_SCROLLLOCK": "0x47",
    "KEY_PAUSE": "0x48",
    "KEY_INSERT": "0x49",
    "KEY_HOME": "0x4a",
    "KEY_PAGEUP": "0x4b",
    "KEY_DELETE": "0x4c",
    "KEY_END": "0x4d",
    "KEY_PAGEDOWN": "0x4e",
    "KEY_RIGHT": "0x4f",
    "KEY_LEFT": "0x50",
    "KEY_DOWN": "0x51",
    "KEY_UP": "0x52",
    "KEY_NUMLOCK": "0x53",
    "KEY_KPSLASH": "0x54",
    "KEY_KPASTERISK": "0x55",
    "KEY_KPMINUS": "0x56",
    "KEY_KPPLUS": "0x57",
    "KEY_KPENTER": "0x58",
    "KEY_KP1": "0x59",
    "KEY_KP2": "0x5a",
    "KEY_KP3": "0x5b",
    "KEY_KP4": "0x5c", 
    "KEY_KP5": "0x5d", 
    "KEY_KP6": "0x5e", 
    "KEY_KP7": "0x5f", 
    "KEY_KP8": "0x60",
    "KEY_KP9": "0x61",
    "KEY_KP0": "0x62",
    "KEY_KPDOT": "0x63" , 
    "KEY_102ND": "0x64",
    "KEY_COMPOSE": "0x65",
    "KEY_POWER": "0x66",
    "KEY_KPEQUAL": "0x67",
    "KEY_F13": "0x68",
    "KEY_F14": "0x69",
    "KEY_F15": "0x6a",
    "KEY_F16": "0x6b",
    "KEY_F17": "0x6c",
    "KEY_F18": "0x6d",
    "KEY_F19": "0x6e",
    "KEY_F20": "0x6f",
    "KEY_F21": "0x70",
    "KEY_F22": "0x71",
    "KEY_F23": "0x72",
    "KEY_F24": "0x73",
    "KEY_OPEN": "0x74",
    "KEY_HELP": "0x75",
    "KEY_PROPS": "0x76",
    "KEY_FRONT": "0x77",
    "KEY_STOP": "0x78",
    "KEY_AGAIN": "0x79",
    "KEY_UNDO": "0x7a",
    "KEY_CUT": "0x7b",
    "KEY_COPY": "0x7c",
    "KEY_PASTE": "0x7d",
    "KEY_FIND": "0x7e",
    "KEY_MUTE": "0x7f",
    "KEY_VOLUMEUP": "0x80",
    "KEY_VOLUMEDOWN": "0x81",
    "KEY_KPCOMMA": "0x85",
    "KEY_RO": "0x87",
    "KEY_KATAKANAHIRAGANA": "0x88",
    "KEY_YEN": "0x89",
    "KEY_HENKAN": "0x8a",
    "KEY_MUHENKAN": "0x8b",
    "KEY_KPJPCOMMA": "0x8c",
    "KEY_HANGEUL": "0x90",
    "KEY_HANJA": "0x91",
    "KEY_KATAKANA": "0x92",
    "KEY_HIRAGANA": "0x93",
    "KEY_ZENKAKUHANKAKU": "0x94",
    "KEY_KPLEFTPAREN": "0xb6",
    "KEY_KPRIGHTPAREN": "0xb7",
    "KEY_LEFTCTRL": "0xe0",
    "KEY_LEFTSHIFT": "0xe1",
    "KEY_LEFTALT": "0xe2",
    "KEY_LEFTMETA": "0xe3",
    "KEY_RIGHTCTRL": "0xe4",
    "KEY_RIGHTSHIFT": "0xe5",
    "KEY_RIGHTALT": "0xe6",
    "KEY_RIGHTMETA": "0xe7",
    "KEY_MEDIA_PLAYPAUSE": "0xe8",
    "KEY_MEDIA_STOPCD": "0xe9",
    "KEY_MEDIA_PREVIOUSSONG": "0xea",
    "KEY_MEDIA_NEXTSONG": "0xeb",
    "KEY_MEDIA_EJECTCD": "0xec",
    "KEY_MEDIA_VOLUMEUP": "0xed",
    "KEY_MEDIA_VOLUMEDOWN": "0xee",
    "KEY_MEDIA_MUTE": "0xef",
    "KEY_MEDIA_WWW": "0xf0",
    "KEY_MEDIA_BACK": "0xf1",
    "KEY_MEDIA_FORWARD": "0xf2",
    "KEY_MEDIA_STOP": "0xf3",
    "KEY_MEDIA_FIND": "0xf4",
    "KEY_MEDIA_SCROLLUP": "0xf5",
    "KEY_MEDIA_SCROLLDOWN": "0xf6",
    "KEY_MEDIA_EDIT": "0xf7",
    "KEY_MEDIA_SLEEP": "0xf8",
    "KEY_MEDIA_COFFEE": "0xf9",
    "KEY_MEDIA_REFRESH": "0xfa",
    "KEY_MEDIA_CALC": "0xfb"
}